apiVersion: kdb.io/v1alpha1
kind: Redis
metadata:
  name: example-redis-1
  namespace: default
spec:
  domain: test-redis-1.tcplb.nortezh.com
  storage:
    pvcName: example-redis-1-data
    size: 1Gi
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
    # mountPath: /data  # optional, this is the default
