apiVersion: kdb.io/v1alpha1
kind: Postgres
metadata:
  name: example-pg-1
  namespace: default
spec:
  user: postgres
  password: postgres
  storage:
    pvcName: example-pg-1-data
    size: 1Gi
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
    # mountPath: /var/lib/postgresql/data  # optional, this is the default
