apiVersion: kdb.io/v1alpha1
kind: Mongo
metadata:
  name: example-mongo-2
  namespace: default
spec:
  domains:
    - test-mongo-2.tcplb.nortezh.com
  user: mongo
  password: mongo
  storage:
    pvcName: example-mongo-2-data
    size: 1Gi
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
