apiVersion: v1
kind: Namespace
metadata:
  name: kdb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kdb-operator
  namespace: kdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdb-operator
rules:
  - apiGroups: ["kdb.io"]
    resources: ["postgres", "redis", "mongo"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kdb.io"]
    resources: ["postgres/status", "redis/status", "mongo/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutetcps", "tlsoptions"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kdb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kdb-operator
subjects:
  - kind: ServiceAccount
    name: kdb-operator
    namespace: kdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdb-operator
  namespace: kdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdb-operator
  template:
    metadata:
      labels:
        app: kdb-operator
    spec:
      serviceAccountName: kdb-operator
      containers:
        - name: operator
          image: k3d-registry.localhost:5000/kdb-operator:latest
